In [1]:
import numpy as np
np.__version__

'1.12.1'

In [3]:
# Create a simple numpy array
ar1 = np.array([1,2,3,4,5])
ar1

array([1, 2, 3, 4, 5])

In [4]:
# Find the type
type(ar1)

numpy.ndarray

In [6]:
np.size(ar1)

5

In [9]:
ar1.dtype

dtype('int64')

In [10]:
ar2 = np.array([1.0,2.0,3.0])
ar2.dtype

dtype('float64')

In [11]:
ar3 = np.array([1,1.0])
ar3.dtype

dtype('float64')

In [12]:
ar3

array([ 1.,  1.])

In [14]:
ar4 = np.array([1,1.0,'Hello'])
ar4.dtype
ar4

array(['1', '1.0', 'Hello'], 
      dtype='<U32')

In [15]:
# shorthand to repeat a sequence n times
ar5 = np.array([0]*10)
ar5

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
# Convert Python range to np array
ar6 = np.array(range(10))
ar6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# create a numpy of zeroes
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [21]:
# force to get only integers
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
# make a range starting at 1 for 10 values
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# range value but increment by 2
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [28]:
# integers in reverse order
np.arange(15,10,-1)

array([15, 14, 13, 12, 11])

In [34]:
# linspace similar to array but produces exact number of items between start and end values
np.linspace(0,5,2)

array([ 0.,  5.])

In [37]:
# multiply array elements
ar7 = np.arange(0,10)
ar7 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
# addition of 2 arrays
ar8 = np.arange(10,20)
ar7 + ar8

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [40]:
# create a matrix
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
m = np.arange(0,20).reshape(5,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [45]:
# Get the size of the matrix
np.size(m)

20

In [46]:
# Get the size of the row (0 -> row)
np.size(m,0)

5

In [47]:
# Get the size of the column (1 -> Col)
np.size(m,1)

4

In [48]:
# select an element -> row 1 col2
m[1,2]

6

In [49]:
# select a row
m[2,]

array([ 8,  9, 10, 11])

In [51]:
# select a column
m[:,3]

array([ 3,  7, 11, 15, 19])

In [52]:
# which items are less than 2
arr8 = np.arange(10)
arr8 < 2

array([ True,  True, False, False, False, False, False, False, False, False], dtype=bool)

In [54]:
(arr8 < 2) | (arr8 > 5)

array([ True,  True, False, False, False, False,  True,  True,  True,  True], dtype=bool)